---
name: make
on:
  push:
    branches:
      - master
jobs:
  make:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: yegor256/plum@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - run: mkdir gh-pages
      - run: cp target/index.html gh-pages
      - uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: gh-pages
          clean: false
